platform: linux
image_resource:
  type: docker-image
  source: {repository: maven, tag: 3.3.9-jdk-8}

inputs:
  - name: source

outputs:
  - name: release-source

run:
  path: /bin/bash
  args:
    - source/ci/tasks/release.sh
